name: CI deploy
on: 
  push:
    branches: ["main"]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: config JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Instala Docker Compose
      run: |
        curl -L "https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: roda docker compose
      run: docker-compose up -d

    - name: Deploy para EC2
      env: 
        PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        USER: ubuntu
        HOST: 54.198.40.22
      run: |
        echo "$PRIVATE_KEY" > aluraChave.pem
        chmod 600 aluraChave.pem

        docker save -o vollmed-api.tar vollmed-api_api

        scp -o StrictHostKeyChecking=no -i aluraChave.pem vollmed-api.tar $USER@$HOST:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i aluraChave.pem init.sql $USER@$HOST:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i aluraChave.pem docker-compose-prod.yaml $USER@$HOST:/home/ubuntu/
        scp -o StrictHostKeyChecking=no -i aluraChave.pem script-deploy.sh $USER@$HOST:/home/ubuntu/  

        ssh -i aluraChave.pem $USER@$HOST "chmod +x script-deploy.sh && ./script-deploy.sh"
